version: "3.8"

services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    networks:
      - doctor-patient-app-network
      
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: usama
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: doctor_patient_db
    ports:
      - "3307:3306"
    networks:
      - doctor-patient-app-network
    volumes:
      - doctor-patient-app_volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  doctor-patient-app-network:
    driver: bridge

volumes:
  doctor-patient-app_volume: